class ProfessionService {
  static final List<String> states = [
    'Doctor',
    'Nurse',
    'Pharmacist',
    'Surgeon',
    'Teacher',
    'Professor',
    'Tutor',
    'Software Engineer',
    'Software Developer',
    'Software Tester',
    'Data Scientist',
    'IT Professional',
    'Web Developer',
    'Cyber Security Expert',
    'System Analyst',
    'Researcher',
    'Graphic Designer',
    'Civil Engineer',
    'Electrical Engineer',
    'Mechanical Engineer',
    'Aeronautical Engineer',
    'Accountant',
    'Auditor',
    'Manager',
    'HR Professional',
    'Marketing Professional',
    'Writer',
    'Photographer',
    'Video Editor',
    'Actor',
    'Musician',
    'Journalist',
    'Lawyer',
    'Judge',
    'Police Officer',
    'Military Officer',
    'Civil Servant',
    'Politician',
    'Chef',
    'Baker',
    'Carpenter',
    'Plumber',
    'Electrician',
    'Painter',
    'Banker',
    'Financial Analyst',
    'Economist',
    'Student',
    'Housewife',
    'Farmer',
    'Self Employed',
    'Freelancer',
    'Unemployed',
  ];

  static List<String> getSuggestions(String query) {
    List<String> matches = [];
    matches.addAll(states);
    matches.retainWhere((s) => s.toLowerCase().contains(query.toLowerCase()));
    return matches;
  }
}